// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUpq2tr7lRLIaxYUStGFEiTNJYenSaasg',
    appId: '1:929379219500:android:9221e0c7d2f1433b6fb989',
    messagingSenderId: '929379219500',
    projectId: 'in-chat-f038d',
    storageBucket: 'in-chat-f038d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtF7jTjbszJre15UqYDGBBB1wTwWeOneg',
    appId: '1:929379219500:ios:1ccd8e06758b0ffa6fb989',
    messagingSenderId: '929379219500',
    projectId: 'in-chat-f038d',
    storageBucket: 'in-chat-f038d.appspot.com',
    androidClientId: '929379219500-2knkjjc37qrjnuhn078j3ju1uelndcag.apps.googleusercontent.com',
    iosClientId: '929379219500-h5ikeo3dlftodq0uk0et66bv91bqc8li.apps.googleusercontent.com',
    iosBundleId: 'com.example.inChat',
  );
}
